version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vitasoft-test-task
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    image: backend
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"